config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get '/contacts/auth/telegram/callback', to: 'contacts#telegram_login', as: :telegram_login

  resources :contacts

  post '/contacts/send_message', to: 'contacts#send_message', as: :send_message

  resources :shareable_link, only: [:show, :create]

  get 'pages/about', to: 'pages#about', as: :about

  match '*unmatched', to: 'application#error_not_found', via: :all, as: :error
end

app/views/shared/404.html.erb
<div class="container-fluid min-vh-100 d-flex flex-column justify-content-center align-items-center">
  <div class="error-message m-5 d-flex flex-column justify-content-center align-items-center">
    <h1 class=" text-center mt-4">Página Não Encontrada...</h1>
    <%= image_tag("error_message.jpeg", class: "img-fluid my-4") %>
    <%= link_to "Clique para voltar para civilização", contacts_path, class: "text-reset text-decoration-none inside-link mb-5" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-auto">
  <div class="container">
    <div class="row">
      <div class="text-center"><i class="fa-solid fa-ellipsis fs-3"></i></div>
      <div class="row text-center">
        <div class="col-md-4 box">
          <ul class="list-inline quick-links">
            <li class="list-inline-item">
              <%= link_to "Sobre esse webapp", about_path, class: "text-reset text-decoration-none inside-link fs-6" %>
            </li>
          </ul>
        </div>
        <div class="col-md-4 box fs-6">
          <p>Made by Marcos, with love</p>
        </div>
        <div class="col-md-4 box">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="https://github.com/marcosgabriel-smc" target="_blank">
                <i class="fa-brands fa-github text-decoration-none footer-icon fs-3"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.linkedin.com/in/marcosgabriel-costa/" target="_blank">
                <i class="fab fa-linkedin-in text-decoration-none footer-icon fs-3"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://soundcloud.com/marcos-gabriel-7" target="_blank">
                <i class="fa-brands fa-soundcloud text-decoration-none footer-icon fs-3"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>