config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get '/contacts/auth/telegram/callback', to: 'contacts#telegram_login', as: :telegram_login

  resources :contacts

  post '/contacts/send_message', to: 'contacts#send_message', as: :send_message

  resources :shareable_link, only: [:show, :create]

  get 'pages/about', to: 'pages#about', as: :about

  match '*unmatched', to: 'application#error_not_found', via: :all, as: :error
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :birthday, presence: true
  validates :name, uniqueness: { scope: :user_id, notice: 'Já existe um contato com essas informações' }

  def self.today_birthdays
    where('EXTRACT(month FROM birthday) = ? AND EXTRACT(day FROM birthday) = ?', Date.today.month, Date.today.day)
  end

  def self.group_contacts_by_month(contacts)
    sorted_contacts = contacts.sort_by { |contact| [contact.birthday.month, contact.birthday.day] }

    contacts_map = {
      january: [],
      february: [],
      march: [],
      april: [],
      may: [],
      june: [],
      july: [],
      august: [],
      september: [],
      october: [],
      november: [],
      december: []
    }

    sorted_contacts.each do |contact|
      month_name = contact.birthday.strftime('%B').downcase.to_sym
      contacts_map[month_name] << contact
    end

    contacts_map
  end

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [:name],
    using: {
      tsearch: { prefix: true}
    }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[update destroy]
  before_action :authorize_user, except: %i[index]
  before_action :set_contacts_and_user, only: %i[index create update]

  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = @user
    if @contact.save
      redirect_to contacts_path, notice: 'Aniversariante adicionado'
    else
      flash.now[:alert] = 'Não foi possível criar o aniversariante'
      render :index, status: :unprocessable_entity
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: 'Aniversariante atualizado.'
    else
      flash.now[:alert] = 'Não foi possível atualizar o aniversariante'
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path notice: 'Aniversariante excluído'
  end

  def telegram_login
    telegram_id = params[:id]

    user = User.find_by(telegram_id: telegram_id)

    if user
      sign_in(user)
      redirect_to contacts_path, notice: 'Acesso via Telegram realizado'
    else
      @new_user = User.new(
        telegram_id: params[:id],
        first_name: params[:first_name],
        last_name: params[:last_name]
      )
      render 'devise/registrations/new'
    end
  end

  def send_message
    TelegramMailer.send_birthday_message.deliver_now
    redirect_to contacts_path, notice: 'Messages delivered.'
  end

  private

  def authorize_user
    contact = @contact || Contact
    authorize contact
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :birthday)
  end

  def set_contacts_and_user
    @user = current_user
    if params[:query].present?
      @contacts = policy_scope(Contact).search_by_name(params[:query])
    else
      @contacts = policy_scope(Contact)
    end

    @grouped_contacts = Contact.group_contacts_by_month(@contacts)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_edit_contact_modal.html.erb
<!-- Button trigger modal for edit -->
<a type="button" class="fa-regular fa-pen-to-square text-reset" data-bs-toggle="modal" data-bs-target="#editContactModal"></a>
<!-- Modal for edit -->
<div class="modal fade" id="editContactModal" tabindex="-1" aria-labelledby="editContactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editContactModalLabel">Editar aniversariante</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(contact, method: :patch) do |f| %>
          <div class="form-inputs">
            <%= f.input :name, input_html: { value: contact.name }, label: "Nome" %>
            <%= f.input :birthday, order: [:day, :month, :year], input_html: { value: contact.birthday }, label: "Data de Aniversário" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-contacts"><%= f.button :submit, 'Atualizar' %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/_new_contact_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn inside-link btn-contacts w-100" data-bs-toggle="modal" data-bs-target="#newContactModal">
  Adicionar aniversariante!
</button>
<!-- Modal -->
<div class="modal fade" id="newContactModal" tabindex="-1" aria-labelledby="newContactModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="newContactModalLabel">Adicione um novo aniversariante</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for(contact, data: { controller: "datepicker" } ) do |f| %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= f.label :name, "Nome" %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.label :birthday, "Data de Aniversário" %>
            <div>
              <%= f.date_field :birthday, order: [:day, :month, :year], class: "form-control birthday-date" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Adicionar", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/_setting_menu.html.erb
<div class="dropdown">
  <button class="btn inside-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Configurações
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Edite sua conta",  edit_user_registration_path, class: "inside-link text-reset dropdown-item"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "inside-link text-reset dropdown-item" %></li>
  </ul>
</div>

app/views/contacts/_sharing_link_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn inside-link btn-contacts w-100" data-bs-toggle="modal" data-bs-target="#sharingLinkModal">
  Compartilhar sua lista!
</button>
<!-- Modal -->
<div class="modal fade" id="sharingLinkModal" tabindex="-1" aria-labelledby="sharingLinkModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="sharingLinkModalLabel">Compartilhe o link!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <a href="<%= ENV['CALLBACK_URL'] %>/shareable_link/<%= user.shareable_token %>" target="_blank", class="text-break">
          <%= ENV['CALLBACK_URL'] %>/shareable_link/<%= user.shareable_token %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container min-vh-100 d-flex flex-column align-items-center justify-content-center">
  <div class="main-page contacts-display p-0 d-flex flex-column">
    <div class="w-100 d-flex justify-content-end">
      <%= render "setting_menu" %>
    </div>
    <div class="contacts-wrapper">
      <div class="d-flex flex-column justify-content-center mt-0 mb-3">
        <h1 class="index-title text-center">Aniversariantes Cadastrados</h1>
        <div class="row align-items-center mt-4">
          <div class="col-md mb-3 d-flex justify-content-center">
            <%= render "new_contact_modal", contact: @contact %>
          </div>
          <div class="col-md-6 mb-3">
            <%= form_with url: contacts_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query,
              params[:query],
              class: "form-control custom-search-input",
              placeholder: "Encontre um contato"
            %>
              <%= submit_tag "Procurar", name: "", class: "btn btn-contacts" %>
            <% end %>
          </div>
          <div class="col-md mb-3 d-flex justify-content-center">
            <%= render "sharing_link_modal", user: @user %>
          </div>
        </div>
      </div>
      <% if params[:query].present? %>
        <% @grouped_contacts.each do |month, contacts| %>
          <% if contacts.present? %>
            <h3 class="month-written text-end"><%= t("date.month_names")[Date::MONTHNAMES.index(month.to_s.capitalize)] %></h3>
          <% end %>
          <% contacts.each do |contact| %>
            <div class="d-flex justify-content-between">
              <div class="d-flex flex-column mb-2">
                <h5 class="mb-0 contact-name"><%= contact.name.capitalize %></h5>
                <%= content_tag(:span, I18n.l(contact.birthday, format: '%d de %B'), class: "date-written fs-6 fst-italic") %>
              </div>
              <ul>
                <%= render "edit_contact_modal", contact: contact %>
                <%= link_to(
                  "",
                  contact_path(contact),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: 'You sure?'
                  },
                  class: "fa-solid fa-trash h-auto ms-2 text-reset"
                ) %>
              </ul>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <% @grouped_contacts.each do |month, contacts| %>
          <h3 class="month-written text-end"><%= t("date.month_names")[Date::MONTHNAMES.index(month.to_s.capitalize)] %></h3>
          <% if contacts.empty? %>
            <p class="date-written fs-6 fst-italic text-center">Sem aniversariantes cadastrados no mês...</p>
          <% else %>
            <% contacts.each do |contact| %>
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-column mb-2">
                  <h5 class="mb-0 contact-name"><%= contact.name.capitalize %></h5>
                  <%= content_tag(:span, I18n.l(contact.birthday, format: '%d de %B'), class: "date-written fs-6 fst-italic") %>
                </div>
                <ul>
                  <%= render "edit_contact_modal", contact: contact %>
                  <%= link_to(
                    "",
                    contact_path(contact),
                    data: {
                      turbo_method: :delete,
                      turbo_confirm: 'Certeza que deseja excluir esse contato?'
                    },
                    class: "fa-solid fa-trash h-auto ms-2 text-reset"
                ) %>
                </ul>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- <%= link_to "Send Messages", send_message_path, data: { turbo_method: :post } %> -->
</div>