config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    root 'devise/sessions#new'
  end

  get '/contacts/auth/telegram/callback', to: 'contacts#telegram_login', as: :telegram_login

  resources :contacts

  post '/contacts/send_message', to: 'contacts#send_message', as: :send_message

  resources :shareable_link, only: [:show, :create]

  get 'pages/about', to: 'pages#about', as: :about

  match '*unmatched', to: 'application#error_not_found', via: :all, as: :error
end

app/controllers/shareable_link_controller.rb
class ShareableLinkController < ApplicationController
  before_action :authenticate_user!

  def show
    authorize :shareable_link, :show?
    @user = current_user
    @sharing_user = User.find_by(shareable_token: params[:id])

    if params[:query].present? && @sharing_user.present?
      current_user_contacts = current_user.contacts.pluck(:name, :birthday)
      @contacts = @sharing_user.contacts.where.not(
        name: current_user_contacts.map(&:first),
        birthday: current_user_contacts.map(&:last)
      ).search_by_name(params[:query]).order(:name)
    elsif @sharing_user.present?
      current_user_contacts = current_user.contacts.pluck(:name, :birthday)
      @contacts = @sharing_user.contacts.where.not(
        name: current_user_contacts.map(&:first),
        birthday: current_user_contacts.map(&:last)
      ).order(:name)
    else
      error_not_found
    end
  end

  def create
    authorize :shareable_link, :create?

    shared_contact = Contact.find(params[:contact_id])

    # Create a new contact instance for the current user using the information from the shared contact
    new_contact = Contact.new(
      name: shared_contact.name,
      birthday: shared_contact.birthday,
      user: current_user
    )

    if new_contact.save
      render json: { success: true, message: 'Aniversariante adicionado!' }
    else
      render json: { success: false, message: 'Já existe um aniversariante com essas informações.' }, status: :unprocessable_entity
    end
  end
end

app/helpers/shareable_link_helper.rb
module ShareableLinkHelper
end

app/views/shareable_link/show.html.erb
<div class="container min-vh-100 d-flex flex-column align-items-center justify-content-center" data-controller="shareable-link">
  <div class="main-page contacts-display p-0 d-flex flex-column">
    <div class="w-100 d-flex justify-content-start">
      <%= link_to "<- Voltar aos seus Contatos", contacts_path, class: "text-reset mx-2 inside-link" %>
    </div>
    <div class="contacts-wrapper mt-3">
      <div class="d-flex flex-column justify-content-center mt-0 mb-3">
        <h1 class="index-title text-center">Adicione os aniversariantes de <%= @sharing_user.first_name %> à sua conta!</h1>
        <div class="w-100 my-3 contacts-wrapper d-flex justify-content-center">
          <%= form_with url: shareable_link_path(id: @sharing_user.shareable_token), method: :get, class: "d-flex sharing-search-bar" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control custom-search-input",
              placeholder: "Encontre um contato"
            %>
            <%= submit_tag "Procurar", name: "", class: "btn btn-contacts" %>
          <% end %>
        </div>
      </div>
      <div class="contacts-wrapper">
        <% @contacts.each do |contact| %>
          <div class="contact-container d-flex justify-content-between month-written my-3" data-shareable-link-target="contact" data-contact-id="<%= contact.id %>">
            <div class="d-flex flex-column mb-1">
              <h5 class="mb-0 contact-name"><%= contact.name.capitalize %></h5>
              <%= content_tag(:span, I18n.l(contact.birthday, format: '%d de %B'), class: "date-written fs-6 fst-italic") %>
            </div>
            <button class="btn d-flex align-items-center" data-action="click->shareable-link#addContact" data-contact-id="<%= contact.id %>">
              <p class="my-0" data-contact-id="<%= contact.id %>">Adicionar</p>
              <i class=" mx-2 my-0 fa-solid fa-person-circle-plus" data-contact-id="<%= contact.id %>"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>